import { atomWithStorage } from "jotai/utils";

export interface Game {
  id: number;
  title: string;
  url: string;
  platform: "Flash Game" | "PS1" | "PS2";
  available: boolean;
  links?: { id: number; url: string }[];
  playableOnPhone: boolean;
  image: string;
  swf?: string;
  useRuffle?: boolean;
}

export const games: Game[] = [
  {
    id: 0,
    title: "Stan Skate",
    url: "https://www.youtube.com/embed/aLmmE8ihKdI",
    image: "https://i.ytimg.com/vi/xrfx8tab5aQ/maxresdefault.jpg",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/1640__stan-skates.swf",
  },
  {
    id: 1,
    title: "Bubble Trouble",
    url: "https://www.youtube.com/embed/BGpij9BGSYo",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/bubbletroubleCdn.swf",
  },
  {
    id: 2,
    title: "Crypt Raider",
    url: "https://www.youtube.com/embed/U3SA9DAAvaE",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/CryptRaider.swf",
  },
  {
    id: 3,
    title: "Bush Shootout",
    url: "https://www.youtube.com/embed/5gpZdxTP_aU",
    image: "",
    available: true,
    playableOnPhone: true,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/bush-shoot-out-389.swf",
  },
  {
    id: 4,
    title: "Spiderman 2000",
    url: "https://www.youtube.com/embed/ClghQ1KevD4",
    links: [{ id: 0, url: "https://www.play-games.com/game/30768/spider-man-2000.html" }],
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "PS1",
  },
  {
    id: 5,
    title: "Pepsiman",
    url: "https://www.youtube.com/embed/iy2OYaS2eyM",
    links: [{ id: 0, url: "https://www.retrogames.cc/embed/42754-pepsiman-japan.html" }],
    image: "",
    available: true,
    playableOnPhone: true,
    platform: "PS1",
  },
  {
    id: 6,
    title: "Tom And Jerry: Fists Of Fury",
    url: "https://www.youtube.com/embed/KOUGAFdVmo8",
    links: [{ id: 0, url: "https://www.retrogames.cc/embed/32832-tom-and-jerry-in-fists-of-furry-usa.html" }],
    image: "",
    available: true,
    playableOnPhone: true,
    platform: "PS1",
  },
  {
    id: 7,
    title: "25 To Life",
    url: "https://www.youtube.com/embed/dViUzEcTOyA",
    links: [{ id: 0, url: "https://placeholder-link.com" }],
    image: "",
    available: false,
    playableOnPhone: false,
    platform: "PS2",
  },
  {
    id: 8,
    title: "Circus Charlie",
    url: "https://www.youtube.com/embed/_JysmzZG_qQ",
    image: "",
    available: true,
    playableOnPhone: true,
    platform: "Flash Game",
    useRuffle: false,
  },
  {
    id: 9,
    title: "The Incredibles: Rise of the Underminer",
    url: "https://www.youtube.com/embed/D0UvfNQZDKQ",
    links: [{ id: 0, url: "https://placeholder-link.com" }],
    image: "",
    available: false,
    playableOnPhone: false,
    platform: "PS2",
  },
  {
    id: 10,
    title: "Pink Panther",
    url: "https://www.youtube.com/embed/OdMGHjIrOB8",
    links: [{ id: 0, url: "https://www.retrogames.cc/embed/42265-pink-panther-pinkadelic-pursuit.html" }],
    image: "",
    available: true,
    playableOnPhone: true,
    platform: "PS1",
  },
  {
    id: 11,
    title: "Heli Attack 3",
    url: "https://www.youtube.com/embed/ZVTTS4t8vsQ",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/ha3miniclip.swf",
  },
  {
    id: 12,
    title: "Royal Rampage",
    url: "https://www.youtube.com/embed/V4nn6gsIsqs",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/1451__bushroyalrampage.swf",
  },
  {
    id: 13,
    title: "Obama Alien Defense",
    url: "https://www.youtube.com/embed/slsaUl9g4JY",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/obama-alien-defense.swf",
  },
  {
    id: 14,
    title: "Hotdog Bush",
    url: "https://www.youtube.com/embed/5C1P45gn6-g",
    image: "",
    available: true,
    playableOnPhone: true,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/hot_dog_bush.swf",
  },
  {
    id: 15,
    title: "Hobo Prison Brawl",
    url: "https://www.youtube.com/embed/qzmg3X4ux5A",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/hoboprisonbrawl.swf",
  },
  {
    id: 16,
    title: "Samurai Jack: Code of the Samurai",
    url: "https://www.youtube.com/embed/6U2qouei2I0",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/codeofthesamurai.swf",
  },
  {
    id: 17,
    title: "Stan James: Freekick Challenge",
    url: "https://www.youtube.com/embed/9B-H2ELbyi4",
    image: "",
    available: true,
    playableOnPhone: true,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/stanjames.swf",
  },
  {
    id: 18,
    title: "Hide The Fart",
    url: "https://www.youtube.com/embed/M2zM8GbDu3k",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/hidethefart.swf",
  },
  {
    id: 19,
    title: "Cat VS Dog",
    url: "https://www.youtube.com/embed/stsbVLIaBrs",
    image: "",
    available: true,
    playableOnPhone: true,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/fleabagvsmutt.swf",
  },
  {
    id: 20,
    title: "Drunk Man Run",
    url: "https://www.youtube.com/embed/gUkjz7Nz_qA",
    image: "",
    available: true,
    playableOnPhone: true,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/drunk-man-run.swf",
  },
  {
    id: 21,
    title: "3 Foot Ninja",
    url: "https://www.youtube.com/embed/Go5sKpm9aJE",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/3-foot-ninja.swf",
  },
  {
    id: 22,
    title: "Fireboy And Watergirl",
    url: "https://www.youtube.com/embed/omv4-cX6DtU",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/foresttemple.swf",
  },
  {
    id: 23,
    title: "Fancy Pants Adventure World",
    url: "https://www.youtube.com/embed/l_vll3EglxA",
    image: "",
   available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/Fancy-Pants.swf",
  },
  {
    id: 24,
    title: "Reel Gold",
    url: "https://www.youtube.com/embed/bO8sCl0oWMc",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/reel-gold.swf",
  },
  {
    id: 25,
    title: "Panik In Chocoland",
    url: "https://www.youtube.com/embed/zQNg3aDnKKM",
    image: "",
    available: true,
    playableOnPhone: false,
    platform: "Flash Game",
    useRuffle: true,
    swf: "/games/Panik.swf",
  },
];

export const videosAtom = atomWithStorage<Game[]>("games", games);
